CREATE TABLE IF NOT EXISTS `MMM_PRESSROOM` (
  `PRESSROOMID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(250) NOT NULL,
  `IMAGEPATH` varchar(255) DEFAULT NULL,
  `NEWSPAPERLINK` varchar(300) DEFAULT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `REMARKS` varchar(255) DEFAULT NULL,
  `ACTIVE` varchar(6) DEFAULT NULL,
  `CREATEDBY` int(11) DEFAULT NULL,
  `CREATED_DATETIME` datetime DEFAULT NULL,
  `UPDATEDBY` int(11) DEFAULT NULL,
  `UPDATED_DATETIME` datetime DEFAULT NULL,
  `MEDIATYPE` varchar(20) DEFAULT NULL,
  `THUMBNAIL` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`PRESSROOMID`)
) ENGINE=InnoDB AUTO_INCREMENT=100000000 DEFAULT CHARSET=latin1;